database:
  address: '127.0.0.1:3306'
  database:
  username:
  password:
ui:
  slot: 27
  title: "&l[ 签到 ]"
  items:
    cant_claim:
      item: EMPTY_MAP
      name: "&f第 {day} 天"
      glow: false
      lore:
        - '&f{reward_name}'
        - '&f'
        - '&c未到签到时间'
    can_claim:
      item: MAP
      name: "&f第 {day} 天"
      glow: true
      lore:
        - '&f{reward_name}'
        - '&f'
        - '&e点击签到'
    claimed:
      item: PAPER
      name: "&f第 {day} 天"
      glow: false
      lore:
        - '&f{reward_name}'
        - '&f'
        - '&a已完成签到'
message: '&a签到奖励发放:&b{format_name}'
day1:
  name: "&f+ &a&l1000&2经验"
  format_name: "&b经验*1000"
  commands:
    - '[CMD] axp {player} addxp 1000'
day2:
  name: "&f+ &5100烟雨币"
  format_name: "&b烟雨币*100"
  commands:
    - '[CMD] p give {player} 100'
day3:
  name: "&f+ &b2大喇叭"
  format_name: "&b大喇叭*2"
  commands:
    - '[CMD] servershout balance give {player} SHOUT 2'
day4:
  name: "&f+ &a&l2000&2经验"
  format_name: "&b经验*2000"
  commands:
    - '[CMD] axp {player} addxp 2000'
day5:
  name: "&f+ &b2大喇叭"
  format_name: "&b大喇叭*2"
  commands:
    - '[CMD] servershout balance give {player} SHOUT 2'
day6:
  name: "&f+ &7&l1000银币"
  format_name: "&b银币*1000"
  commands:
    - '[CMD] rme add {player} bal 1000'
day7:
  name: "&f+ &6&l100金币"
  format_name: "&b金币*100"
  commands:
    - '[CMD] rme add {player} gold 100'
